name: exa_api
description: A pure dart SDK for the Exa API.
version: 1.1.1
homepage: https://exa.ai/

environment:
  sdk: ^3.8.1

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.5.4
  lints: ^5.0.0
  test: ^1.24.0
  json_serializable: ^6.9.5
